# Generated by Django 3.2.6 on 2021-10-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
